import type { Metadata } from "next";
import "@/app/styles/globals.css";
import Header from "@/app/components/layout/Header";


export const metadata: Metadata = {
  title: "Commecial Website",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <Header />
          <main>
          {children}
          </main>
      </body>
    </html>
  );
}
